---
title: "ixpantia sesion_2: coerciones"
output: learnr::tutorial
runtime: shiny_prerendered
description: >
  Ejercicios de pizarra que se realizan durante la sesión para aprender sobre
  coerciones en R.
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
library(lubridate)
library(dplyr)
library(readxl)
library(readr)
library(dplyr)

vector_1 <- c(10, 20, 30)
vector_2 <- c("a", "b", "c")
vector_3 <- c(TRUE, FALSE, TRUE)
prueba_vector<-c(20, 40, "A", 80)
class(prueba_vector)
prueba_vector
vector_prueba_1 <- c(20, 40, TRUE, 80)
vector_prueba_2 <- c("R","ixpantia", "RStudio", 2)
vector_prueba_3 <- c(20:60)
vector_prueba_4 <- c(letters)
vector_prueba_5 <- c(TRUE, TRUE, FALSE, 0,0,1)

vector_prueba_1_nuevo <- as.numeric(vector_prueba_1)
vector_prueba_2_nuevo <- as.logical(vector_prueba_2)
vector_prueba_2_nuevo <- as.logical(vector_prueba_2)
vector_prueba_4_nuevo <- as.numeric(vector_prueba_4)
vector_prueba_5_nuevo <- as.logical(vector_prueba_5)
```


## Datos
```{r echo=TRUE, message=TRUE}
vector_prueba_1
vector_prueba_2
vector_prueba_3
vector_prueba_4
vector_prueba_5
```


**¿Qué cree que ha pasado con la letra que había inicialmente en el vector_prueba_1?**
```{r v1, exercise = TRUE}

```


**¿Qué ocurre con los datos de vector_prueba_2? ¿En qué se convierten?**
```{r v2, exercise = TRUE}

```


**¿Podríamos ahora sacar el promedio del vector_prueba_3?**
```{r v3, exercise = TRUE}

```


**¿Qué ha pasado con vector_prueba_4?**
```{r v4, exercise = TRUE}

```


**¿Qué tenemos ahora con el vector_prueba_5?**
```{r v5, exercise = TRUE}

```



