---
title: "ixpantia sesion_6: programar_dplyr"
output: learnr::tutorial
runtime: shiny_prerendered
description: >
  Ejercicios de pizarra que se realizan durante la sesión para aprender sobre
  programar con dplyr.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(learnr)
library(dplyr)
library(purrr)
library(rlang)
library(readr)
library(janitor)
library(lubridate)
library(readxl)

indice_salarial <- read_excel("PJCROD_INDICESALARIAL_V1.xls") %>% 
  mutate(salario_antes = as.numeric(Salario_Base_Ant),
         salario_actual = as.numeric(Salario_Base_Act),
         indice = as.numeric(I_C_S))
```

## Datos de la sesión

### Indice Salarial del Poder Judicial
```{r}
glimpse(indice_salarial)
```

## Preguntas

### Pregunta 1 
```{r exp, exercise = TRUE, error = TRUE}
mi_exp_mal <- (indice_salarialPJ$salario_antes * indice_salarialPJ$salario_actual) / indice_salarialPJ$indice
mi_exp <- quote((indice_salarialPJ$salario_antes * indice_salarialPJ$salario_actual) / indice_salarialPJ$indice) 

qq_show(
  indice_salarialPJ %>% 
  mutate(mi_exp)
)

qq_show(
  indice_salarialPJ %>% 
  mutate(!!mi_exp)
)
```

Para crear funciones con gramática tidyverse:
```{r gramatica, exercise = TRUE}
indice_salarialPJ %>%
  group_by(TN_Cod_Clase) %>%
  summarise(
    avg = mean(salario_actual, na.rm = TRUE)
  )
```

### Pregunta 2
```{r promedio, exercise = TRUE}
calcula_promedio <- function(data, columna) {
  data %>%
    group_by(TN_Cod_Clase) %>% 
    summarise(avg = mean(.data[[columna]], na.rm = TRUE))
}

calcula_promedio(data = indice_salarialPJ, columna =  "salario_actual")

qq_show(calcula_promedio(data = indice_salarialPJ, columna =  "salario_actual"))
```

### Pregunta 3
```{r promedio2, exercise = TRUE}
calcula_promedio <- function(data, columna, grupo) {
  data %>%
    group_by({{grupo}}) %>% 
    summarise(avg = mean(.data[[columna]], na.rm = TRUE))
}

calcula_promedio(data = indice_salarialPJ, columna = "salario_actual", grupo = R_E_F_J)
```

### Pregunta 4
```{r clase, exercise = TRUE}
promedio_por_clase <- function(datos_abiertos, clase) {
  
  indice_salarialPJ %>% 
    filter(TC_Des_Clase == {{clase}}) %>% 
    summarise(
      promedio = mean(salario_actual, na.rm = TRUE)
    )
}

promedio_por_clase(datos_abiertos = indice_salarialPJ,
                   clase = "AUXILIAR  ADMINISTRATIVO")
```

### Pregunta 5
```{r agrupacion, exercise = TRUE}
agrupacion_total <- function(datos_abiertos, ...) {
  
  agrupacion <- enquos(...)
  
  datos_abiertos %>% 
  group_by(!!!agrupacion) %>% 
  summarise(
    total = n()
  )
}

agrupacion_total(datos_abiertos = indice_salarialPJ, 
                 ... =  R_E_F_J, TN_Cod_Clase)
```
